import torch
import torch.nn as nn
import torch.nn.functional as F


#1. Constant Initialization (nn.init.constant_) : Generally used for biases, almost never for weights.
layer = nn.Linear(5, 5)

# Initialize weights to 0.01 (Not recommended for deep layers)
nn.init.constant_(layer.weight, 0.01)

# Initialize bias to 0 (Common practice)
nn.init.constant_(layer.bias, 0)

#2. Xavier (Glorot) Initialization
#nn.init.xavier_uniform_This fills the tensor with values sampled from a uniform distribution U(-a, a)
#Best for: Tanh or Sigmoid activations.

layer = nn.Linear(10, 10)
nn.init.xavier_uniform_(layer.weight)

#3. Kaiming (He) Initialization : . It accounts for the fact that ReLU neurons 
# "kill" half of the input (values < 0), so it compensates by making the initial weights larger.
# Usage: This is the default for most ReLU-based architectures (ResNet, etc.).
# Best for: ReLU, Leaky ReLU, and PReLU activations.

layer = nn.Linear(10, 10)

# 'nonlinearity' helps the function calculate the correct gain
nn.init.kaiming_uniform_(layer.weight, nonlinearity='relu')


#1. CNN (Conv2d)
#Since CNNs are almost always paired with ReLU activations 
# (like in ResNet or VGG), kaiming_uniform_ is the best choice. 
# It ensures that the signal doesn't die out as it passes through many convolutional filters.

#2. Linear (Dense)
#If the Linear layer is your "output" layer or uses a Tanh/Sigmoid activation, 
# xavier_uniform_ is the standard. 
# If it's a hidden layer followed by ReLU, you could also use Kaiming here.

#3. Attention (MultiheadAttention)Attention mechanisms rely heavily on Dot Products (Q * K^T). 
# If the weights are too large, the dot products explode, pushing the Softmax into 
# regions where gradients are nearly zero.
#Xavier is the gold standard for Attention because it keeps the variance of the 
# projections (Query, Key, Value) controlled, ensuring the Softmax stays in a "sensitive" range.

#4. All Biases	constant_(0)	Simplest starting point; prevents early shift in data.
class MyModel(nn.Module):
    def __init__(self):
        super().__init__()
        # CNN Layer
        self.conv = nn.Conv2d(3, 16, kernel_size=3)
        # Linear Layer
        self.fc = nn.Linear(16 * 26 * 26, 128)
        # Simplified Attention (Multihead)
        self.attn = nn.MultiheadAttention(embed_dim=128, num_heads=4)

    def forward(self, x):
        # ... forward pass logic ...
        return x

def init_weights(m):
    """
    Function to be applied to each layer of the network
    """
    # For Convolutional layers - Use Kaiming (Standard for Computer Vision)
    if isinstance(m, nn.Conv2d):
        nn.init.kaiming_uniform_(m.weight, nonlinearity='relu')
        if m.bias is not None:
            nn.init.constant_(m.bias, 0)

    # For Linear layers - Use Xavier or Kaiming
    elif isinstance(m, nn.Linear):
        nn.init.xavier_uniform_(m.weight)
        nn.init.constant_(m.bias, 0)

    # For Attention layers
    elif isinstance(m, nn.MultiheadAttention):
        # Attention involves several internal weight matrices (in_proj, out_proj)
        nn.init.xavier_uniform_(m.in_proj_weight)
        nn.init.constant_(m.in_proj_bias, 0)
        nn.init.xavier_uniform_(m.out_proj.weight)
        nn.init.constant_(m.out_proj.bias, 0)

# 1. Instantiate the model
model = MyModel()

# 2. Apply the initialization function
model.apply(init_weights)


#Deformable attention (Deformable DETR, Custom Position Aware Attention)
#1. Grid Initialization (Uniform)
#If your reference points represent coordinates in a 2D space (like an image),
# you shouldn't initialize them randomly. If you do, the model might "miss" 
# certain corners of the image during early training. Instead, we initialize them as a uniform grid.

import torch
import torch.nn as nn

def init_reference_points(m):
    if hasattr(m, 'reference_points'):
        # Example: Creating a 2D grid (H x W)
        H, W = 8, 8 
        # Generate linear spacing from 0.05 to 0.95
        ref_y, ref_x = torch.meshgrid(
            torch.linspace(0.5, H - 0.5, H),
            torch.linspace(0.5, W - 0.5, W),
            indexing='ij'
        )
        # Normalize to [0, 1] range
        ref_y = ref_y.reshape(-1)[None] / H
        ref_x = ref_x.reshape(-1)[None] / W
        
        # Stack into (x, y) coordinates
        ref_points = torch.stack((ref_x, ref_y), -1) 
        
        # Initialize the parameter
        m.reference_points.data.copy_(ref_points)
        print("Reference points initialized to a uniform grid.")

# Usage in a layer
class DeformableAttention(nn.Module):
    def __init__(self, num_points=64):
        super().__init__()
        # Reference points are usually learned, but need a good start
        self.reference_points = nn.Parameter(torch.zeros(1, num_points, 2))

attn_layer = DeformableAttention()
init_reference_points(attn_layer)


# 2. Linear/MLP-based Reference Points
# Sometimes reference points are generated by a small Linear layer (an "offset predictor"). In this case, we want the initial output to be zero (no offset) so the model starts by looking at the default grid.
# Weight: nn.init.constant_(m.weight, 0)
# Bias: nn.init.constant_(m.bias, 0)

# The layer that predicts where to move the reference points
offset_predictor = nn.Linear(128, 2) 

# Initialize to zero so that initially, offsets are 0
nn.init.constant_(offset_predictor.weight, 0)
nn.init.constant_(offset_predictor.bias, 0)